</section>
<!-- end of main section -->
<!-- footer -->
<footer id="footer">
	<div class="warning">
	<h3>Risk Warning</h3>
	<p>Spread betting, CFDs and FX are leveraged products and carry a high level of risk to your capital as prices may move rapidly against you. It is possible to lose more than your initial investment and you may be required to make further payments. These products may not be suitable for all customers therefore ensure you understand the risks and seek independent advice. </p>
	</div>

	<menu class="legal"><p><a href="http://www.cmcmarkets.co.uk/legal/spreadbetting">Legal</a> | <a href="http://www.cmcmarkets.co.uk/contact-us">Contact us</a></p></menu>  
</footer>
<!-- end of footer -->
    
</body>