<?php
  /**
   * Set the gradient div for all pages
   */
  ?>


<header id="header">
		<div class="logo"><img src="/profiles/cmc_installer/themes/cmc_registration_form/images/logo-reg.png"  alt="Logo"></div>
	   <h1 id="page-title"><?php print $title; ?></h1>
		 <!-- fill in image for bottom of comp screen image -->
		<div class="ptfrm"></div>
	
		<!-- <?php
			    // main header section
				// print render($page['header']);
				  ?> -->

	    <!-- <?php print render($page['menu_bar']); ?> -->
	</div>
	
</header>
	<!-- end of header -->
	
	<!-- main section -->
   <section class="main">

